AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  ApiKey:
    Type: String
    NoEcho: true

Resources:
  LogPlayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        Fn::Transform:
          Name: 'AWS::Include'
          Parameters:
            Location: openapi.yml
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          LoggingLevel: INFO
          MetricsEnabled: true
          ThrottlingRateLimit: 1
          ThrottlingBurstLimit: 1
#      AccessLogSetting:
#        DestinationArn: !GetAtt ApiGatewayLoggingRole.Arn
#        # https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html
#        Format: '$context.httpMethod $context.resourcePath $context.integration.status'
  GetGameRecord:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./log-play-lambda/target/log-play-app.jar
      Handler: pl.zajacp.GetGameRecordHandler
      Runtime: java17
      MemorySize: 512
      Timeout: 10
      Description: Get single game
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GamesLogTable
      Environment:
        Variables:
          GAMES_LOG_TABLE: !Ref GamesLogTable
          API_KEY: !Ref ApiKey
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref LogPlayApi
            Path: /games
            Method: GET
  GetGamesLog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./log-play-lambda/target/log-play-app.jar
      Handler: pl.zajacp.GetGamesLogHandler
      Runtime: java17
      MemorySize: 512
      Timeout: 10
      Description: Get all games
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GamesLogTable
      Environment:
        Variables:
          GAMES_LOG_TABLE: !Ref GamesLogTable
          API_KEY: !Ref ApiKey
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref LogPlayApi
            Path: /games/log
            Method: GET
  PutGameRecord:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./log-play-lambda/target/log-play-app.jar
      Handler: pl.zajacp.PutGameRecordHandler
      Runtime: java17
      MemorySize: 512
      Timeout: 10
      Description: Put single games
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GamesLogTable
      Environment:
        Variables:
          GAMES_LOG_TABLE: !Ref GamesLogTable
          API_KEY: !Ref ApiKey
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref LogPlayApi
            Path: /games
            Method: PUT
  PutGamesLog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./log-play-lambda/target/log-play-app.jar
      Handler: pl.zajacp.PutGamesLogHandler
      Runtime: java17
      MemorySize: 512
      Timeout: 10
      Description: Put multiple games
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GamesLogTable
      Environment:
        Variables:
          GAMES_LOG_TABLE: !Ref GamesLogTable
          API_KEY: !Ref ApiKey
      Events:
        Api:
          Type: Api
          Properties:
            Path: /games/log
            Method: PUT
  HealthCheckLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./log-play-lambda/target/log-play-app.jar
      Handler: pl.zajacp.HealthCheckHandler
      Runtime: java17
      MemorySize: 512
      Timeout: 5
      Description: Health check for Games Log database
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref GamesLogTable
      Environment:
        Variables:
          GAMES_LOG_TABLE: !Ref GamesLogTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref LogPlayApi
            Path: /healthcheck
            Method: GET
  GamesLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userName
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: userName
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
#  ApiGatewayLoggingRole:
#    Type: AWS::IAM::Role
#    Properties:
#      AssumeRolePolicyDocument:
#        Version: '2012-10-17'
#        Statement:
#          - Effect: Allow
#            Principal:
#              Service: apigateway.amazonaws.com
#            Action: sts:AssumeRole
#      ManagedPolicyArns:
#        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
  PzjcDomain:
    Type: 'AWS::ApiGateway::DomainName'
    Properties:
      DomainName: log-play-api.pzjc.pl
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: arn:aws:acm:eu-central-1:469283624338:certificate/a238a992-64af-4c56-9c98-4f285300379d
  PzjcBasePathMapping:
    Type: 'AWS::ApiGateway::BasePathMapping'
    Properties:
      DomainName: !Ref PzjcDomain
      RestApiId: !Ref LogPlayApi
      Stage: Prod
  PzjcRoute53Record:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneName: pzjc.pl.
      Name: log-play-api.pzjc.pl
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt PzjcDomain.RegionalHostedZoneId
        DNSName: !GetAtt PzjcDomain.RegionalDomainName

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://log-play-api.pzjc.pl/Prod/"
  WebDirectEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${LogPlayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"