AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  ApiKey:
    Type: String
    NoEcho: true

Resources:
  GetGameRecord:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./log-play-lambda/target/log-play-app.jar
      Handler: pl.zajacp.GetGameRecordHandler
      Runtime: java17
      MemorySize: 512
      Timeout: 10
      Description: Get single game
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GamesLogTable
      Environment:
        Variables:
          GAMES_LOG_TABLE: !Ref GamesLogTable
          API_KEY: !Ref ApiKey
      Events:
        Api:
          Type: Api
          Properties:
            Path: /games
            Method: GET
  GetGamesLog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./log-play-lambda/target/log-play-app.jar
      Handler: pl.zajacp.GetGamesLogHandler
      Runtime: java17
      MemorySize: 512
      Timeout: 10
      Description: Get all games
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GamesLogTable
      Environment:
        Variables:
          GAMES_LOG_TABLE: !Ref GamesLogTable
          API_KEY: !Ref ApiKey
      Events:
        Api:
          Type: Api
          Properties:
            Path: /games/log
            Method: GET
  PutGameRecord:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./log-play-lambda/target/log-play-app.jar
      Handler: pl.zajacp.PutGameRecordHandler
      Runtime: java17
      MemorySize: 512
      Timeout: 10
      Description: Put single games
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GamesLogTable
      Environment:
        Variables:
          GAMES_LOG_TABLE: !Ref GamesLogTable
          API_KEY: !Ref ApiKey
      Events:
        Api:
          Type: Api
          Properties:
            Path: /games
            Method: PUT
  PutGamesLog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./log-play-lambda/target/log-play-app.jar
      Handler: pl.zajacp.PutGamesLogHandler
      Runtime: java17
      MemorySize: 512
      Timeout: 10
      Description: Put multiple games
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GamesLogTable
      Environment:
        Variables:
          GAMES_LOG_TABLE: !Ref GamesLogTable
          API_KEY: !Ref ApiKey
      Events:
        Api:
          Type: Api
          Properties:
            Path: /games/log
            Method: PUT
  GamesLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userName
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: userName
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  HealthCheckLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./log-play-lambda/target/log-play-app.jar
      Handler: pl.zajacp.HealthCheckHandler
      Runtime: java17
      MemorySize: 512
      Timeout: 5
      Description: Health check for Games Log database
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref GamesLogTable
      Environment:
        Variables:
          GAMES_LOG_TABLE: !Ref GamesLogTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /healthcheck
            Method: GET

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"