export const PLAYERS = [
    "Ja",
    "Ilona",
    "Maciek",
    "Kamil",
    "Łysy",
    "Kofin",
    "Korot",
    "Żulian",
    "Paweł",
    "Czina",
    "Lamdziadek",
    "Wujor",
    "Mona",
    "Dawid",
    "Gosia",
    "Rafał",
    "Kuba",
    "Anastazja",
    "Automa",
    "Monika Pawlińska",
    "Maciek Pawlinski",
    "Pioterek",
    "Gutek",
    "Ewa Gutek",
    "Łukasz Hansi",
    "Dosia Lipka",
    "Natalia",
    "Grzesiek",
    "Wojtek Fb",
    "Michał Fb",
    "Piotrek Fb",
    "Milena",
    "Mama Lucy",
    "Tata Olek",
    "Ewka Korot"]

export const GAMES = [
    "51 stan",
    "7 cudów Armada",
    "7 cudów Pojedynek",
    "7 cudów świata",
    "Aeons End",
    "Agricola",
    "Ark Nova",
    "Arnak",
    "Atiwa",
    "Azul",
    "Blood Rage",
    "Botanik",
    "Brass",
    "Brzdęk",
    "Camel Up",
    "Caverna",
    "Clash of Cultures",
    "Cyklady",
    "Diuna Imperium",
    "Dominant Species",
    "Dominant Species Marine",
    "Everdell",
    "Gloomhaven",
    "Gloomhaven Szczęki Lwa",
    "Great Western Trail",
    "Imperium Antyk",
    "Kaskadia",
    "Kolejowy Szlak",
    "Konspiracja",
    "Kości",
    "Mind Bug",
    "Mur Hadriana",
    "Nemesis",
    "O mój Zboże",
    "Park niedźwiedzi",
    "Podwodne Miasta",
    "Projekt L",
    "Race for the Galaxy",
    "Radlands",
    "Res Arcana",
    "Root",
    "Scythe",
    "Small World of Warcraft ",
    "Summoner Wars",
    "Terraformacja",
    "This War of Mine",
    "Turbo",
    "Viticulture",
    "Welcome To",
    "Wojna o Pierścień ",
    "Woodcraft",
    "Załoga Głębiny",
    "Agricola Chłopi",
    "Eclipse 2nd",
    "Papierowe Podziemia",
    "Wilki"
].sort()